apiVersion: v1
kind: Service
metadata:
  name: dummy-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dummy-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: CONTAINER_IMAGE
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-secret-access-key
          - name: AWS_PARAMETER_STORE_KEY
            value: bancolombia
          - name: AWS_REGION
            value: us-east-1
          ports:
            - containerPort: 8080